### ISSUE TITLE
Fusion table connector lists only subset of fusion tables from google drive

### ISSUE THREAD

**Issue by Krivozhnya** [googledatastudio/community-connectors#10]
The dropdown in fusion connector only shows top 20 or so tables in my google drive. Seems like these are selected by date created in google drive.

**Comment by minhaz** [comment]
Thanks for identifying the issue. We'll look into this. In the meantime, if you are trying to use the connector with a specific fusion table, just replace `request.configParams.tableId` in the code with the id for your fusion table.

*Note for developer: If dropdown is limited to 20 items, we can use a textbox to take a tableid as input that will override the dropdown selection.*

**Comment by diminishedprime** [comment]
The fusion tables connector has been deprecated since fusion tables has also been deprecated.
