### ISSUE TITLE
Can't modify Invalid API Key

### ISSUE THREAD

**Issue by Dallasodem** [googledatastudio/community-connectors#100]
After inputting an invalid API key for Page Speed Insights GDS connector... How do you change it? Tried to remove & deauthorize. But it now defaults to URL input with no option to edit the API Key field. 

Thanks in advance

**Comment by diminishedprime** [comment]
`resetAuth` is called when a connector is revoked through the /datasources/create/ ui. There was a bug that prevented this from happening, but it has since been fixed.

**Comment by diminishedprime** [comment]
You need to revoke the connector through https://datastudio.google.com/c/datasources/create Then when you re-add it, you'll be prompted for the authorization. Note that this only works if the code provided for `resetAuth()` correctly resets the authorization.

**Comment by fabiocesarato** [comment]
Dear @diminishedprime thanks for the help.
Revoking the permissions now all works.
It was not immediately clear for me how to revoke access. I share screen-shots to clarify to other users hoping it will be useful.

![google_data_studio_data_source_speed_insights_revoke_access_1](https://user-images.githubusercontent.com/5769042/51597356-54cf3100-1efb-11e9-84b5-481723fb00fe.PNG)

![google_data_studio_data_source_speed_insights_revoke_access_2](https://user-images.githubusercontent.com/5769042/51597370-58fb4e80-1efb-11e9-9d6b-98a6e985e74d.PNG)
