### ISSUE TITLE
how to connect to OAUTH1 service?

### ISSUE THREAD

**Issue by machinefriendly** [googledatastudio/community-connectors#101]
Hi, 

I searched in the [dev docs](https://developers.google.com/datastudio/connector/reference#authtype), and looks that OAuth1 is not supported, and I try to use oauth1 GAS library while selecting OAUTH2 as auth type, but it doesn't work. I can neither find oauth1 case in sample.

Can you help confirm this? or there is a workaround on this?

Thanks in advance,

**Comment by machinefriendly** [comment]
related issue tracker >> https://issuetracker.google.com/issues/119292472

**Comment by diminishedprime** [comment]
OAUTH1 isn't officially supported, but you should be able to get it to work by having `getAuthType` return `OAUTH2` and using the corresponding GAS library. Make sure you're using the oauth1 gas library which can be found [here].

[here]: https://github.com/gsuitedevs/apps-script-oauth1
