### ISSUE TITLE
Fusion Table Connector error - Community Connector Error

### ISSUE THREAD

**Issue by razwangh** [googledatastudio/community-connectors#110]
There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.

Connector details
There was an error caused by this connector.

**Comment by diminishedprime** [comment]
Could you provide more information on what you were doing and what isn't working?

**Comment by razwangh** [comment]
I am trying to connect my Fusion Table file with DataStudio, in that process when I do add a new connector and select Fusion Table from there it show the above given error.

**Comment by diminishedprime** [comment]
Since we removed the fusion table connector from this repo, this issue is no longer needed.
