### ISSUE TITLE
CRUX thresholds in Data Studio connector are incorrect

### ISSUE THREAD

**Issue by Robin-Lord** [googledatastudio/community-connectors#115]
CRUX Data Studio connector lists thresholds for Fast, Average and Slow which are incorrect. Based on checking how the data lines up with a couple of sites I've put together the attached table which I think shows the correct values

![image](https://user-images.githubusercontent.com/29159105/52657889-9303b300-2ef1-11e9-8f2d-3f7e296046e4.png)

**Comment by diminishedprime** [comment]
@minhaz - could you take a look at this?

**Comment by minhaz** [comment]
RIck is the subject matter expert on this.

**Comment by rviscomi** [comment]
The thresholds in the connector are still showing up as the old incorrect values:

![image](https://user-images.githubusercontent.com/1120896/55824902-d1bd8000-5ad2-11e9-9e2e-764e45b4a7ea.png)

@minhaz has this change been deployed to the public connector?

**Comment by diminishedprime** [comment]
They have not, I'm hoping to redeploy changes to the connectors in this repo soon.
