### ISSUE TITLE
unable to connect the npm downloads

### ISSUE THREAD

**Issue by ebidel** [googledatastudio/community-connectors#116]
I'm unable to connect the npm downloads to a project.

```
Debug
npm Downloads by Google Data Studio Developer Relations

Cannot set aggregation type for field: downloads since it is not reaggregatable.

getSchema:110
```

**Comment by diminishedprime** [comment]
Thanks for the bug report! I'll try to fix this soon.

**Comment by z0mg** [comment]
This is a hugely spread issue. You need to ditch the .setAggregation(aggregations.SUM) call and then select SUM in the fields config wizard step.
Anxiously waiting for this fix as well.

**Comment by diminishedprime** [comment]
I have addressed this bug and the fix should be rolling out in the next few days. For the time being, to fix in connector code, just add `.setIsReaggregatable(true)` to all fields that have a  call to `.setAggregation(...)`

**Comment by nhoj01** [comment]
I was working on the codelab "Get Started with Community Connectors" and could not complete the step "Configure the connector", adding the _.setIsReaggregatable(true)_ under the filed listed below fixed the issue. 

Thanks!  


 `fields.newMetric()
    .setId('downloads')
    .setType(types.NUMBER)
    .setAggregation(aggregations.SUM)
`

**Comment by LASERKing2** [comment]
learn

**Comment by diminishedprime** [comment]
This bug has been fixed. The DataStudioApp builder for fields should have defaulted to setting `isReaggregatable` to true (as our legacy docs detail), but it was defaulting to false. This coupled with new validation to make sure you don't accidentally set a defaultAggregationType for a field that can't be aggregated caused the issue. Thanks everyone for their patience.
