### ISSUE TITLE
Couldn't find the AWS athena connector

### ISSUE THREAD

**Issue by vishnuvvn** [googledatastudio/community-connectors#121]
Hi,

I tried to use AWS athena connector but couldn't find it in the community connectors section. Has it not been released yet?

**Comment by diminishedprime** [comment]
That is correct, hopefully it'll be released by some time next week.

**Comment by vishnuvvn** [comment]
Okay great. Will wait to hear from you.

**Comment by diminishedprime** [comment]
I created a deployment here:

https://datastudio.google.com/datasources/create?connectorId=AKfycbzBYBRgWS8yaLCQkOKAKqMdG85XxPwcxmVFGdglGN-1Vsb8O4wmpS7Kfac7VRR2MM7n

But I can't test it since I don't have aws credentials. @vishnuvvn - would you mind trying this out and let me know if it's working?

**Comment by brunovilar** [comment]
@diminishedprime, the connector is working properly. Thank you for the deployment.

**Comment by diminishedprime** [comment]
Okay, thanks. If it is working, I'll add it to the product gallery soon.
