### ISSUE TITLE
Firebase error when creating CrUX Dashboard

### ISSUE THREAD

**Issue by rviscomi** [googledatastudio/community-connectors#124]
For example, when entering `https://web.dev` as the origin, I get this error:

```
TypeError: Expected argument of type object, but instead had type object.

fbCache:86
processFirebase:48
getOriginDataset:529
getSchema:381
```

`fbCache` is the function name in which the error occurred and it does the Firebase caching.

`https://www.example.com` is an example of another origin that triggers the error.

Oddly, when I enter `https://developers.google.com` and some other origins, I don't get the error.

Looking at the Stack Driver error logs, it seems to happen when the origin is not in the Apps Script cache and the Firebase cache lookup fails.

**Comment by minhaz** [comment]
I didn't have the most updated code in the repo. Committed and pushed the code. Reverted the prod deployment to last working version. Once the PR is approved, I'll updated Prod again with the new version of code.
