### ISSUE TITLE
Is there a way to reset the API Key for a connector 

### ISSUE THREAD

**Issue by grantkemp** [googledatastudio/community-connectors#144]
I noticed there is a `resetAuth` method in the DS connector API but I can't see an easy way to use it. 

Eg Page Speed Insights Connector which uses the following auth type: 
```
function getAuthType() {
  return {
    type: 'KEY'
  };
}
```
 If the user puts in an API key that ceases to work - is there a way to remove the old API Key and reset the connector back to default?

**Comment by diminishedprime** [comment]
The way to make `resetAuth` get called is to go to the page to [create a new data source], find the connector in the list, click on the three dots, and then click `revokeAccess`. We know this is a bit of a pain, we're hoping to make this process easier in the future. 

[create a new data source]: https://datastudio.google.com/c/u/0/datasources/create
