### ISSUE TITLE
Migrate the page speed insights Connector to v5 of the API

### ISSUE THREAD

**Issue by grantkemp** [googledatastudio/community-connectors#145]
Page Speed insights is still using the old version of the api which no longer reflects the data shown in the page speed insights page.  

We should 
- Update the api to v5
- Split out mobile and desktop into seperate metrics so they can easily be shown in 2 scorecards without needing to add a filter to each one.
- If we get some time - do a count of the number of opportunities to improve the performance. ( this should act as a preamble to showing the body of the opportunities directly in Data Studio)

**Comment by diminishedprime** [comment]
We're now using v5 of the api so closing this issue.
