### ISSUE TITLE
Google Sign In is disabled for Meetup connector

### ISSUE THREAD

**Issue by maracharnell** [googledatastudio/community-connectors#150]
While on datastudio.google.com, I am unable to create a new DataStudio data source using the Meetup connector. Specifically, when I try to authorize the connector, I get "Sign in with Google temporarily disabled for this app". Usually I am able to click a link to bypass this step, but there's no option like that on this window:  

![Screen Shot 2019-03-27 at 3 28 29 PM](https://user-images.githubusercontent.com/49006272/55116633-2f9aa280-50a5-11e9-85c8-3d05afd74e70.png)

**Comment by alintz** [comment]
I would love to see if this can be fixed. Meetup recently switched from API keys to Oauth, which broke my homegrown method of data collection. This would be a lifesaver.

**Comment by diminishedprime** [comment]
Hi all, to fix this issue we need to change the caching to not use sheets. Once we're no longer using sheets, we won't be requesting sensitive OAuth scopes, and we will no longer be required to get this "app" verified by Google. I'm hoping to get around to fixing this sometime this quarter.

**Comment by ehmelo** [comment]
Any news on that matter?

**Comment by diminishedprime** [comment]
This deployment for JSON connect is no longer supported. If you would like to use this connector, please deploy it yourself using [these instructions].

[these instructions]: https://github.com/googledatastudio/community-connectors/tree/master/meetup#set-up-the-community-connector-for-personal-use
