### ISSUE TITLE
contribute a new connector 

### ISSUE THREAD

**Issue by benknaan** [googledatastudio/community-connectors#151]
in simple works with explanation how do I contribute my connector
https://github.com/benknaan/datastudio-community-connector-Alma-Analytics
to this community.
I tried to post 'pull request' but it didn't work.

**Comment by diminishedprime** [comment]
Please see [Creating a pull request] from the GitHub documentation.

But before you create one, please make sure this connector doesn't make more sense as a partner connector. Please see [Publish a Community Connector] for a table that outlines why you might make a partner connector instead. 

[Publish a Community Connector]: https://developers.google.com/datastudio/connector/publish-connector
[Creating a pull request]: https://help.github.com/en/articles/creating-a-pull-request
