### ISSUE TITLE
Problem with pull request new Data Source from Senuto

### ISSUE THREAD

**Issue by analityka** [googledatastudio/community-connectors#170]
Hi,

I would like to add Senuto Data Source to googledatastudio / community-connectors

I have created new accounts on github: analityka@senuto.com
I have created accounts on https://script.google.com on analityka@senuto.com

I have created a few pull request, I have accepted CLA, but always was problem with CLA

Best Regards
Mike

**Comment by diminishedprime** [comment]
Looks like you got this working with #172
