### ISSUE TITLE
USER_TOKEN not valid in manifest authType

### ISSUE THREAD

**Issue by buzzware** [googledatastudio/community-connectors#177]
![image](https://user-images.githubusercontent.com/28285/58760328-d9485500-8568-11e9-9e59-5a36fda124a9.png)

If I change USER_TOKEN to USER_PASS and save, it is accepted, but USER_TOKEN is rejected with the shown error.

**Comment by diminishedprime** [comment]
Thanks for the report. This will be fixed soon.

**Comment by diminishedprime** [comment]
This is now fixed. Thanks for the issue.

**Comment by buzzware** [comment]
Is it deployed? I still get the same error

**Comment by diminishedprime** [comment]
Oh, you're right, It's in the process of being deployed now, expect it to be live in the next few days. Sorry for jumping the gun!

**Comment by diminishedprime** [comment]
The change is now live.
