### ISSUE TITLE
JSON-connect - Adding HTTP headers when connecting

### ISSUE THREAD

**Issue by kadrikiisk** [googledatastudio/community-connectors#185]
JSON-connect

Would be great if the "JSON connect" data connector could take HTTP headers as input also when making the connection, in addition to plain URL.

Or is there any other way to pass the HTTP headers when making the connection?

For example:
URL:   https://my-url.org/json
HTTP headers (JSON):  {"authkey": "xxxx"}

**Comment by diminishedprime** [comment]
JSON-connect will currently only work for end points that don't require authentication. Since a community connector can only support one `AUTH_TYPE` at a time, we would need another connector for JSON data that needs auth in the header.

**Comment by kadrikiisk** [comment]
Thank you for responding, I understand.

But are there any plans on making another connector that would support auth headers?

**Comment by diminishedprime** [comment]
There are no plans from me, but feel welcome to send a PR for another connector that does this.
