### ISSUE TITLE
Senuto Image broken

### ISSUE THREAD

**Issue by diminishedprime** [googledatastudio/community-connectors#189]
The image for the Senuto connector doesn't display properly since it's not sized properly. The connector image should be 40x40 px.

**Comment by diminishedprime** [comment]
@analityka - Could you look into this?

**Comment by analityka** [comment]
Hi,

I changed image logo to small one 40x40 px :)
My pull request is waiting  :)

**Comment by diminishedprime** [comment]
Thanks! Fixed by #190
