### ISSUE TITLE
error caused by this connector

### ISSUE THREAD

**Issue by Ganesh96** [googledatastudio/community-connectors#195]
Connector details
There was an error caused by this connector.

Error ID: a1d4e7c4

**Comment by diminishedprime** [comment]
Could you clarify which connector you were using when you experienced this issue?

**Comment by zdigit** [comment]
There was a problem with a comment in code that was not clearly marked with //. From line 49 of Code.gs. It should look like this:
 //Intro Quick Survey
//Overview of Community Connectors
//Community Connector Workflow
//Set up your Apps Script project
//Define getAuthType()
//Define getConfig()
//Define getSchema()
//Define getData() : Part 1
//Define getData() : Part 2
//Define getData() : Part 3
//Update manifest
//Test your connector in Data Studio
//Next steps
//close
//Connect and visualize all your data in Data Studio
//access_time
//9 mins remaining
//11. Define getData() : Part 3

//Your combined getData() code will look like the one below. Add the following code to your Code.js file:

//Code.js

**Comment by diminishedprime** [comment]
I was just able to create a new data source using the [npm connector]. Let me know if you're still having an issue with this and we can re-open this issue.

[npm connector]: https://datastudio.google.com/c/datasources/create?connectorId=AKfycbx_QrjRgS_9pK5fKckj1sqgKEDuvmedjImSPMzDPzQ_sH5mkVdilBOypA4ANmQWCrfRTg
