### ISSUE TITLE
Error After Authentication

### ISSUE THREAD

**Issue by esdrasdemorais** [googledatastudio/community-connectors#196]
Community Connector Error

There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.
Connector details

There was an error caused by this connector.

**Comment by diminishedprime** [comment]
Could you clarify which connector you were using when you experienced this issue?

**Comment by torvalde** [comment]
I experienced it with the firestore connector, maybe it is for several ones....

**Comment by wgcv** [comment]
Me also 
<img width="1069" alt="Screen Shot 2019-06-22 at 11 32 11 PM" src="https://user-images.githubusercontent.com/8989089/59971661-fcea3400-9545-11e9-8d01-bd8534cebee1.png">

**Comment by diminishedprime** [comment]
This error should be fixed for the firestore connector now.
