### ISSUE TITLE
JSON Connect Connector Issue

### ISSUE THREAD

**Issue by romaniv1024** [googledatastudio/community-connectors#214]
Get error when connect to Data Studio.

![Знімок екрана з 2019-07-08 19-54-27](https://user-images.githubusercontent.com/22196861/60828178-74f96080-a1ba-11e9-997b-bfc76d9ef5ce.png)

**Comment by diminishedprime** [comment]
We're currently working on getting all of the open-source connectors verified.

**Comment by abrambailey** [comment]
Just stumbled on this myself. Any idea about ETA?

**Comment by diminishedprime** [comment]
This deployment for JSON connect is no longer supported. If you would like to use this connector, please deploy it yourself using [these instructions].

[these instructions]: https://github.com/googledatastudio/community-connectors/tree/master/JSON-connect#set-up-the-community-connector-for-personal-use
