### ISSUE TITLE
JSON Connect Connector Issue

### ISSUE THREAD

**Issue by polluct** [googledatastudio/community-connectors#217]
google login temporarily deactivated/not possible

**Comment by Divan369** [comment]
I am also having the same issue, is there a way to bypass this while we wait for google to verify this open-source connector?

**Comment by caiolocalsearch** [comment]
Same here!

**Comment by romaniv1024** [comment]
Duplicate of #214

**Comment by diminishedprime** [comment]
This deployment for JSON connect is no longer supported. If you would like to use this connector, please deploy it yourself using [these instructions].

[these instructions]: https://github.com/googledatastudio/community-connectors/tree/master/JSON-connect#set-up-the-community-connector-for-personal-use
