### ISSUE TITLE
Removing Senuto from Open Source Gallery

### ISSUE THREAD

**Issue by diminishedprime** [googledatastudio/community-connectors#219]
Just a heads up, @analityka, In light of the recent changes for OAuth verification, We now recommend that you manage your own deployment. If you would like this connector to be listed in the gallery, you'll need to go through the partner publishing process. If you want your code to be removed from this repo, let me know, but feel free to keep it in.

**Comment by analityka** [comment]
Hi Matt,

We need to be your *Partner* (many of our clients use datastudio with
Senuto data source)

Would you enable as open source for a while until we become a partner -
please

We have partner requirements Done

Best Regards
Analityka

**Comment by analityka** [comment]
Is there any possibility now for our clients to use the senuto datastudio?

**Comment by diminishedprime** [comment]
Sorry, we are no longer able to have non-google connectors in the "open-source" section of Data Studio. I would recommend starting the [partner publishing process]. For the time being, you can [share your connector] with clients directly.

Apologies for the policy change,
Matt

[share your connector]:https://developers.google.com/datastudio/connector/share
[partner publishing process]: https://developers.google.com/datastudio/connector/pscc-requirements
