### ISSUE TITLE
Firestore Connector Issue

### ISSUE THREAD

**Issue by esdrasdemorais** [googledatastudio/community-connectors#250]
FireStore Community Connector From https://github.com/googledatastudio/community-connectors/tree/master/firestore Doesn't Work.

Help me Please.

**Comment by esdrasdemorais** [comment]
TypeError: Cannot find function getAuthToken in object [object Object]. (line 47, file "Firestore")

**Comment by diminishedprime** [comment]
Duplicate of #251

**Comment by fye-campbell** [comment]
Did you make any progress with this?  I think I'm having the same issue.
