### ISSUE TITLE
child process via shell command considered harmful

### ISSUE THREAD

**Issue by Lucretiel** [googledatastudio/community-connectors#26]
https://github.com/googledatastudio/community-connectors/blob/87896569ac4e999da4c29be6a832aa6bba1220a6/cc-util/update-readme.js#L50

Generally, using the shell to open child processes is considered harmful, as it opens the user up to shell injection vulnerabilities if they're not careful. It's fine in this case, because the command is a hard-coded string, but it's probably worth changing as a matter of best practice.

See also the [discussion of the same issue](https://docs.python.org/2/library/subprocess.html#frequently-used-arguments) in Python's similar subprocess module.

In this case, it would probably be preferable to use [child_process.execFile](https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback), which has a built-in option for changing the working directory.

**Comment by diminishedprime** [comment]
Good catch. In this case, we should just remove the cc-util folder in its entirety. It's not being used, and probably shouldn't have been added in the first place.

**Comment by diminishedprime** [comment]
closing in favor of #27
