### ISSUE TITLE
JSON Connect Connector Issue

### ISSUE THREAD

**Issue by chrisipop** [googledatastudio/community-connectors#261]
![Screenshot 2019-08-21 at 10 41 04](https://user-images.githubusercontent.com/54266622/63421292-40570680-c400-11e9-8868-8786f459e0c6.png)

Ho there. The attached Error is persisting - does the connector rely on a public URL that outputs the JSON?

**Comment by diminishedprime** [comment]
Typically that error means that the endpoint you fetched from returned html instead of json, which is why it's complaining about a `<` character.

**Comment by akimalo** [comment]
@diminishedprime I see the same error, but unfortunately I don't really understand your reply. 
Could u explain is there any way I can fix that? Should I put a < character somewhere?

**Comment by diminishedprime** [comment]
There's probably no way for you to fix this issue. It means that the url that you requested data from is returning the data in the wrong format. There's nothing the connector can do about this other than clearer error messages.
