### ISSUE TITLE
Implement getAuthType() with support for  different credentials (different API key) under 1 account

### ISSUE THREAD

**Issue by asirota** [googledatastudio/community-connectors#262]
We are trying to get our connector through the Partner Connector approval process and got this as one of the issues to fix.

- **Use appropriate authentication method in getAuthType(). Do not request credentials via getConfig().** 

We implemented getAuthType() instead for obvious security issues of storing the API key unencrypted in the configuration. But our connector could work with potentially multiple API keys.

Problem definition: I want to be able to have several data sources, connected to the same service with different credentials. When I try to set credentials or revoke credentials, I don’t have any datasource id (or some other unique context).

 I see that the most common way to store credentials is

```
var props = PropertyService.getUserProperties()
props.setProperty(‘dscc.key’, apikey)

```
But that means, that all data sources store data under the same key. As a result all created data sources will share the same credentials. Could you please suggest some way to store credentials (api key in my case) separately for each data source?

The only way I found is to pass API key through data source config, but it is against requirements to partner connectors.

**Comment by diminishedprime** [comment]
Unfortunately, there's no way to do this right now. Could you please create a feature request in the [issue tracker]?

[public issue tracker]: https://issuetracker.google.com/issues?q=componentid:321382

**Comment by asirota** [comment]
> Unfortunately, there's no way to do this right now. Could you please create a feature request in the [issue tracker]?

Sure. For now we are going to be using a AllowOverride API key config parameter.
