### ISSUE TITLE
gke-usage-metering not fetching data(query produces no results)

### ISSUE THREAD

**Issue by mar1n3r0** [googledatastudio/community-connectors#265]
**Which connector were you using?**

gke-usage-metering

**What's going wrong with this connector?**

The Data Studio template shows no data. 

All tables are in place. Running the query manually produces only unallocated namespace results.

**Comment by karlkfi** [comment]
I'm having the same problem with new reports and explore sessions created from the template.
There's no obvious way to debug the query failure either.

**Comment by mar1n3r0** [comment]
Actually the query can be taken from here: https://github.com/googledatastudio/community-connectors/blob/master/gke-usage-metering/src/query.ts and run in the BigQuery editor.
 After replacing all the variables needed manually it produced an output but all was unallocated resources, hence not detected by the template. It will just require a significant amount of research and trial and error since it's a 200+ lines query...

**Comment by mar1n3r0** [comment]
It's working now seems like the billing needed some time to aggregate the necessary reports before it can produce the result. Marking this as resolved.

**Comment by wwmoraes** [comment]
@mar1n3r0 we're having exactly the same issue. Did you just wait for the billing to build up? How much time it took until your report was producing expected results? Thank you in advance for alswering!

**Comment by mar1n3r0** [comment]
@wwmoraes it took about 24-48 hours if I recall correctly.
