### ISSUE TITLE
Error: ENTITY_NOT_FOUND DATASET_CONFIGURATION

### ISSUE THREAD

**Issue by karlkfi** [googledatastudio/community-connectors#268]
**Which connector were you using?**
GKE Usage Metering

**What's going wrong with this connector?**
Attempting to create a new report after creating and configuring a datasource with the GKE Usage Metering connector causes the following error:
```
)]}'
{"reason":5,"errorStatus":{"reason":5,"code":5,"reasonStr":"ENTITY_NOT_FOUND","errorCategoryStr":"DATASET_CONFIGURATION","category":5,"uniqueErrorCode":"a8576333"},"params":{"errorId":"a8576333"}}
```

**Comment by diminishedprime** [comment]
This issue should now be fixed. Can you try again and let me know if you're still facing this issue?

**Comment by karlkfi** [comment]
Works now, thanks.
