### ISSUE TITLE
Data studio is not able to authorize the kaggle app.

### ISSUE THREAD

**Issue by askaydevs** [googledatastudio/community-connectors#295]
Data studio is not able to authorize the kaggle app.

**Comment by aadlof10** [comment]
having the same issue. Data studio will not allow me to authorize kaggle.

**Comment by Joydeep75** [comment]
same here and getting the error message "Attention: This connector has not been verified or reviewed. It is recommended that you only use community connectors from trusted sources."

**Comment by CharlesWebbMSF** [comment]
getting the same issue as above. I am posting this to show that this is not an isolated issue

**Comment by rkotha82** [comment]
Same here, Data studio will not authorize kaggle. Any inputs?

**Comment by xoelop** [comment]
Same thing here. Any news?

**Comment by morriswong** [comment]
Same here as well

**Comment by Svetonio** [comment]
For me the same.
Someone can explain why?
The same for google fit data source access

**Comment by askaydevs** [comment]
You can follow up this [link](https://support.google.com/accounts/thread/20757484?hl=en) for the latest updates from google community. In case of a found solution, feel free to post here.
