### ISSUE TITLE
Meetup CC connector is not working.

### ISSUE THREAD

**Issue by geovanisouza92** [googledatastudio/community-connectors#51]
It states "Token state is invalid or expired. Try again."

**Comment by diminishedprime** [comment]
I just tried the deployed version of the connector and had no issues. Which deployment id are you using for the connector?

**Comment by geovanisouza92** [comment]
I'm not sure, it's the one provided on Data Studio conector gallery.

**Comment by grantkemp** [comment]
When I just tried it out - I got this error:  I wonder if thats the reason that @geovanisouza92  is having an issue?
<img width="490" alt="screen shot 2018-08-14 at 21 09 45" src="https://user-images.githubusercontent.com/751115/44115703-7c19490e-a006-11e8-9d7d-349297b7bce8.png">

**Comment by grant** [comment]
You can bypass that error by clicking Advanced:
https://developers.google.com/apps-script/guides/client-verification
