### ISSUE TITLE
Npm connector doesn't properly support @ or / in package name

### ISSUE THREAD

**Issue by zol** [googledatastudio/community-connectors#66]
Whilst setting the package name here:

![image](https://user-images.githubusercontent.com/81672/44694385-fec89100-aa21-11e8-8128-b32cdb561bc8.png)

These work:

`react,angular`
`@storybook/react`

However, this fails:

`react,@storybook/react`

With error:

```
Script error message: Error: DS_USER:Unable to fetch data from source.
 Script error cause: USER
 Script error stacktrace: 
  :300
  getData:131
```

I suspect the connector isn't parsing the `@` or `/` characters properly.

**Comment by diminishedprime** [comment]
This repo no longer has the npm-connector.
