### ISSUE TITLE
Add issues & pull requests into GitHub connector. 

### ISSUE THREAD

**Issue by diminishedprime** [googledatastudio/community-connectors#7]
The GitHub connector would be more useful if could also be configured to pull in issues and pull requests for a repository

**Comment by Lucretiel** [comment]
Working on it: 

https://github.com/Lucretiel/datastudio/tree/master/community-connectors/github

**Comment by sebas932** [comment]
+1 !

**Comment by mayd2h** [comment]
There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.

Connector details
There was an error caused by this connector.
