### ISSUE TITLE
Can't connect Firebase to Google Data Studio

### ISSUE THREAD

**Issue by Gonect** [googledatastudio/community-connectors#71]
I'm getting an error message while trying to connect Firebase to Google Data Studio. Anyone with an solution? The error message below:

Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.

Gr. Gert Meeuws, Gonect

**Comment by lumyus** [comment]
Same issue here! Whenever I try to connect Firestore.
Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.

**Comment by fredrivett** [comment]
+1.

Really not sure how Google hasn't verified it's own products to talk to each other. Blocking me from using Google Data Store to query Firestore.

**Comment by odmera** [comment]
Same issue here!I have the same problem, some other alternative?
Another solution may be to send my data with cloud functions to bigQuery and connect data studio with bigQuery?

**Comment by RafaQC** [comment]
> Same issue here... some other alternative?
> Another solution may be to send my data with cloud functions to bigQuery and connect data studio with bigQuery?

I was thinking about sending a JSON to a drive and using the conector for that, since my info is not so big.

**Comment by gasperipi** [comment]
same here.

**Comment by mukeshtaurus** [comment]
Same for me....
Struggling from months

**Comment by jcsalberto** [comment]
Same for me....

**Comment by erikcunha** [comment]
same here...

**Comment by maxnucci** [comment]
+1

**Comment by ra9r** [comment]
Same for me.

**Comment by odmera** [comment]
> > ¿El mismo problema aquí ... alguna otra alternativa? 
> > Otra solución puede ser enviar mis datos con funciones de nube a bigQuery y conectar data studio con bigQuery.
> 
> Estaba pensando en enviar un JSON a una unidad y usar el conector para eso, ya que mi información no es tan grande.



> > Same issue here... some other alternative?
> > Another solution may be to send my data with cloud functions to bigQuery and connect data studio with bigQuery?
> 
> I was thinking about sending a JSON to a drive and using the conector for that, since my info is not so big.

>is also a good option, but I think that this way you should constantly update the json, so you can have reports in real time.

**Comment by odmera** [comment]
> > Same issue here... some other alternative?
> > Another solution may be to send my data with cloud functions to bigQuery and connect data studio with bigQuery?
> 
> I was thinking about sending a JSON to a drive and using the conector for that, since my info is not so big.

is also a good option, but I think that this way you should constantly update the json, so you can have reports in real time.

**Comment by diminishedprime** [comment]
We're hoping to get this connector working again in the future, but for the time-being we removed it from the gallery. If you want to deploy it on your own, you can use the code under the [firestore directory] of this repo, but there is no ETA of when it will be added again. 

[firestore directory]: https://github.com/googledatastudio/community-connectors/tree/master/firestore

**Comment by erikcunha** [comment]
@diminishedprime why ? Can you explain to us ? What's the problem with this conector

**Comment by diminishedprime** [comment]
This connector needs to access sensitive oauth scopes and in order to use those scopes, it has to go through an approval process. This connector isn't officially supported by Google, but on a best-effort basis by me and I don't have the cycles to go through it at the moment.

**Comment by buffolander** [comment]
no news on this?

**Comment by timothy-mccarthyfinch** [comment]
it seems like they have no plans doing it.

I assume the reason is that firebase is sort of new and seperated
