### ISSUE TITLE
GitHub Connector should allow for multiple org/repo pairs

### ISSUE THREAD

**Issue by grant** [googledatastudio/community-connectors#73]
# GitHub Connector should allow for multiple org/repo pairs

Currently you can only add 1 org/repo pair. Example:

![screen shot 2018-09-13 at 14 12 28](https://user-images.githubusercontent.com/744973/45516524-35abe000-b760-11e8-9cc8-45b3147ec21a.png)

**Comment by diminishedprime** [comment]
Good catch! I thought I fixed this bug earlier, but redeployed to the wrong deployment. You should now have the option to allow parameter overriding if you make a new data source with the connector.
