### ISSUE TITLE
Github connector for datastudio does not count # of stars per date

### ISSUE THREAD

**Issue by chrisheecho** [googledatastudio/community-connectors#77]
Not sure when this happened but I used to be able to create a time series graph of accumulated stars over time series. I am unable to do this with the current version of the connector. How can I either

1. Create the accumulated sum of stars in a given org/repo
2. Or please put this feature back to the existing connector

**Comment by dbungard** [comment]
How did you get it to connect at all? I've not been able to get them even talking.

**Comment by chrisheecho** [comment]
I was able to do this before, but it stopped working..not sure exactly when
