### ISSUE TITLE
SQL statement for initial aggregation in Chrome UX connector

### ISSUE THREAD

**Issue by mwhitaker** [googledatastudio/community-connectors#86]
Thank you for making the code available! I'm trying to get this connector to work in my environment and it would be helpful if you could share how you did the initial aggregation from the raw public Bigquery dataset to the one used in your [code](https://github.com/googledatastudio/community-connectors/blob/master/chrome-ux-report/src/Code.js#L27).

If you could point me in the right direction, I'd appreciate it.

Michael

**Comment by rviscomi** [comment]
Hi @mwhitaker, both the query and the materialized table are available here: https://bigquery.cloud.google.com/dataset/chrome-ux-report:materialized (metrics_query and metrics_summary)
