### ISSUE TITLE
Can't connect to firestore. Authorize failed.

### ISSUE THREAD

**Issue by crazygo** [googledatastudio/community-connectors#89]
Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.

**Comment by cthixton** [comment]
Same here:
Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.

**Comment by diminishedprime** [comment]
We're hoping to get this connector working again in the future, but for the time-being we removed it from the gallery. If you want to deploy it on your own, you can use the code under the [firestore directory] of this repo, but there is no ETA of when it will be added again. 

[firestore directory]: https://github.com/googledatastudio/community-connectors/tree/master/firestore
